### ISSUE TITLE
SpaceInputAxis id not taken into account with Pydantic 2.9

### ISSUE THREAD

**Issue by jdeschamps** [bioimage-io/spec-bioimage-io#631] opened 2024-09-06 08:15 UTC
Pydantic 2.9 was released yesterday and it caused ids to not properly validates in `SpaceInputAxis`. Given the following snippet:

``` python
SpaceInputAxis(id=AxisId('x'), size=32)
```

We get different class attributes value depending on the package version.

Pydantic 2.8:
```
> SpaceInputAxis(size=32, id='x', description='', type='space', unit=None, scale=1.0, concatenable=False)
```

Pydantic 2.9:
```
> SpaceInputAxis(size=32, id=None, description='', type='space', unit=None, scale=1.0, concatenable=False)
```

which down the line raises an error when trying to package all this into a `InputTensorDescr`:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for InputTensorDescr
axes
  Value error, Duplicate axis ids: {None} [type=value_error, input_value=[BatchAxis(id='batch', de....0, concatenable=False)], input_type=list]
    For further information visit https://errors.pydantic.dev/2.9/v/value_error
```

**Comment by mese79** [comment] 2024-09-06 15:09
I couldn't find what really causes this problem but if I comment this [line](https://github.com/bioimage-io/spec-bioimage-io/blob/37c310146f649cc80ee695b8e559bc97769c6464/bioimageio/spec/model/v0_5.py#L203):
`NonBatchAxisId = Annotated[AxisId, Predicate(lambda x: x != "batch")]`
The axis will have the given `id`.  
So, instead of `Predicate` from [annotated_types](https://github.com/annotated-types/annotated-types) package, I used pydantic `StringConstraints` with a regex pattern:
`NonBatchAxisId = Annotated[AxisId, StringConstraints(pattern="[^batch$].*")]`
Then the axis will receive the `AxisId` properly.  
```python
from bioimageio.spec.model.v0_5 import SpaceInputAxis

ax1 = SpaceInputAxis(id=AxisId("y"), size=100)
print(ax1)
# size=100 id='y' description='' type='space' unit=None scale=1.0 concatenable=False
```

**Comment by FynnBe** [comment] 2024-09-10 08:02
caused by https://github.com/pydantic/pydantic/issues/10319
fixed on pydantic side with https://github.com/pydantic/pydantic/pull/10321
We should update our pydantic pin as commented in #632 to avoid running into this issue.

**Comment by FynnBe** [comment] 2024-10-10 15:42
issue was in pydantic and has been patched

**Closed by FynnBe** 2024-10-10 15:42 UTC
